# `docker-compose up db`
# Useful for day to day development; when you just want to `iex -S mix phx.start` and have a DB to hit.
#
# `docker-compose up`
# Facilitates quickly building and starting a prod-like stack (containerized OTP release).
#
version: '2'
services:
  db:
    image: postgres:alpine
    ports:
      - "$DB_PORT:$DB_PORT"
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD

  web:
    build:
      context: .
      args:
        APP_NAME: $APP_NAME
        APP_VERSION: $APP_VERSION
    environment:
      DB_URL: "postgres://$DB_USERNAME:$DB_PASSWORD@db:$DB_PORT/$DB_DATABASE"
      DB_POOL_SIZE: $DB_POOL_SIZE
      WEB_PORT: $WEB_PORT
    ports:
      - "$WEB_PORT:$WEB_PORT"
    links:
      - db:db
    depends_on:
      - db
